name: Teardown

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend
        uses: cham207388/github-custom-actions/mvn-jdk21@main
        with:
          directory: ./backend-ald
          test: 'no'
          
      # - name: Build frontend
      #   uses: cham207388/github-custom-actions/vite-node@main
      #   with:
      #     directory: ./web-s3

      - name: Destroy Lambda
        uses: cham207388/github-custom-actions/tf-no-ssh@main
        with:
          directory: ./terraform
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          variables: "acm_certificate_arn=${{ secrets.ACM_CERTIFICATE_ARN }},acm_cert_arn_agw=${{ secrets.ACM_CERT_ARN_AGW }},domain_name=${{ secrets.DOMAIN_NAME }}"
          destroy: "yes"
